on: push
name: Build Test
run-name: "Testing ${{ github.sha }}" 
jobs:
  BuildTest:
    runs-on: ubuntu-latest
    steps:
      #Setup dependencies
      - name: Install JDK 11
        uses: actions/setup-java@v3.10.0
        with:
          java-version: 11
          distribution: adopt 
      - name: Install GCC
        uses: Dup4/actions-setup-gcc@v1
        with:
          version: latest
      - name: Install OpenGL
        uses: openrndr/setup-opengl@v1.1
      
      #Install WPILib
      - name: Retrieve WIPILib Cache
        id: wpilib-cache
        uses: actions/cache/restore@v3.2.6
        with:
          path: allwpilib
          key: wpilib-build 
      - name: Download WPILib
        if: steps.wpilib-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v3.3.0
        with:
          repository: wpilibsuite/allwpilib
          path: allwpilib
          ref: v2023.4.2
      - name: Build WPILib 
        if: steps.wpilib-cache.outputs.cache-hit != 'true'
        run: ./gradlew :wpilibj:build
      - name: Create WPILib Cache
        if: steps.wpilib-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3.2.6
        with:
          key: wpilib-build
          path: /home/runner/work/Robot2023/allwpilib
      - name: Publish WPILib to Local Maven
        run: ./gradlew :wpilibj:publish release
        
      #Test our code
      - name: Checkout Robot Code
        uses: actions/checkout@v3.3.0
      - name: Test Code
        run: ./gradlew build
        
