on: push
name: Build Test
run-name: "Testing ${{ github.sha }} from ${{ github.actor }}" 
jobs:
  build-code:
    #Run on Ubuntu and use WIPILib's RoboRIO Docker container
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2023-22.04
    steps:
      #Clone robot code
      - name: Checkout code
        uses: actions/checkout@v3
      #Make gradlew (gradle) executable
      - name: Make gradlew executable
        run: "chmod +x ./gradlew"
      #Compile robot code
      - name: Build robot code
        run: "./gradlew build"
