on: push
name: Build Test
run-name: Testing 
jobs:
  BuildTest:
    runs-on: ubuntu-latest
    steps:
      #Setup dependencies
      - name: Install JDK 11
        uses: actions/setup-java@v3.10.0
        with:
          java-version: 11
          distribution: adopt 
      - name: Install GCC
        uses: Dup4/actions-setup-gcc@v1
        with:
          version: latest
      
      #Install WPILib
      - name: Cache WPILib Build
        id: wpilib-cache
        uses: actions/cache@v3.2.6
        with:
          path: allwpilib
          key: wpilib-build 
      - name: Download WPILib
        if: steps.wpilib-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v3.2.6
        with:
          repository: wpilibsuite/allwpilib
          ref: v2023.4.2
      - name: Setup WPILib ARM Toolchain
        if: steps.wpilib-cache.outputs.cache-hit != 'true'
        working-directory: ./allwpilib
        run: ./gradlew installRoboRioToolchain
      - name: Build WPILib 
        if: steps.wpilib-cache.outputs.cache-hit != 'true'
        working-directory: ./allwpilib
        run: ./gradlew build
      - name: Publish WPILib to Local Maven
        working-directory: ./allwpilib
        run: ./gradlew publish
      - name: Checkout Robot Code
        uses: actions/checkout@v3.2.6
      - name: Test Code
        run: ./gradlew build
        
